### ISSUE TITLE
Can't load data via RestClient?

### ISSUE THREAD

**Issue by igrigorik** [dcrec1/kilt#3]
<pre>
1 igrigorik ~> kilt-app --check-settings
/opt/local/lib/ruby/gems/1.8/gems/kilt-0.3.0/lib/kilt.rb:39:in `fetch_activities': undefined method `body' for #<RestClient::Response:0x1010f2678> (NoMethodError)
    from /opt/local/lib/ruby/gems/1.8/gems/kilt-0.3.0/lib/kilt.rb:28:in `initialize'
    from /opt/local/lib/ruby/gems/1.8/gems/kilt-0.3.0/lib/kilt.rb:11:in `new'
    from /opt/local/lib/ruby/gems/1.8/gems/kilt-0.3.0/lib/kilt.rb:11:in `init'
    from /opt/local/lib/ruby/gems/1.8/gems/kilt-0.3.0/bin/kilt-app:9
    from /opt/local/bin/kilt-app:19:in `load'
    from /opt/local/bin/kilt-app:19
</pre>

**Comment by dcrec1** [comment]
Hi Ilya,

had you execute kilt-install before kilt-app?

Btw, --check-settings option is not available yet.

**Comment by igrigorik** [comment]
Yep, when I run kilt-app, it sits there for ~20-30 seconds and then throws that exception.

**Comment by dcrec1** [comment]
Hi, which version of rest-client do you have?

Im currently running Kilt with 1.4.2.

Can you also execute the following code with your token please?:

require 'rest_client'
RestClient.get("http://www.pivotaltracker.com/services/v3/activities?limit=10", 'X-TrackerToken' => TOKEN).class

**Comment by igrigorik** [comment]
Aha, an update seems to have done the trick -- haven't seen any notifications yet, but at least its not throwing an error. You might want to add a version dependency to the gemspec.

**Comment by dcrec1** [comment]
Yes, I'll do that, thanks for the feedback :)

**Comment by bullrico** [comment]
I just installed kilt and I get the same error after kilt-app:

/Users/bobby/.rvm/gems/ruby-1.8.7-p249/gems/kilt-0.3.2/lib/kilt.rb:39:in `fetch_activities': undefined method`body' for #RestClient::Response:0x139ce88 (NoMethodError)
    from /Users/bobby/.rvm/gems/ruby-1.8.7-p249/gems/kilt-0.3.2/lib/kilt.rb:28:in `initialize'
    from /Users/bobby/.rvm/gems/ruby-1.8.7-p249/gems/kilt-0.3.2/lib/kilt.rb:11:in`new'
    from /Users/bobby/.rvm/gems/ruby-1.8.7-p249/gems/kilt-0.3.2/lib/kilt.rb:11:in `init'
    from /Users/bobby/.rvm/gems/ruby-1.8.7-p249/gems/kilt-0.3.2/bin/kilt-app:10
    from /Users/bobby/.rvm/gems/ruby-1.8.7-p249/gems/kilt-0.3.2/bin/kilt-app:7:in`fork'
    from /Users/bobby/.rvm/gems/ruby-1.8.7-p249/gems/kilt-0.3.2/bin/kilt-app:7
    from /Users/bobby/.rvm/gems/ruby-1.8.7-p249/bin/kilt-app:19:in `load'
    from /Users/bobby/.rvm/gems/ruby-1.8.7-p249/bin/kilt-app:19

**Comment by dcrec1** [comment]
Hi Bobby, plz update the gem RestClient.

I'll specify in the dependencies the needed version to run Kilt without problems.

**Comment by bullrico** [comment]
That solved it, thanks!

**Comment by ashokraju** [comment]
I'm having this problem even after an update.  This is what I get:

```
C:/Ruby192/lib/ruby/gems/1.9.1/gems/ruby-snarl-0.0.8/lib/snarl.rb:15:in `<module
:SnarlAPI>': uninitialized constant DL::Importable (NameError)
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/ruby-snarl-0.0.8/lib/snarl.rb:1
 4:in `<class:Snarl>'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/ruby-snarl-0.0.8/lib/snarl.rb:7
:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:33:in `require'
    from <internal:lib/rubygems/custom_require>:33:in `rescue in require'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/kilt-0.5.1/lib/kilt.rb:4:in `<t
op (required)>'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/kilt-0.5.1/bin/kilt-app:5:in `<
top (required)>'
    from C:/Ruby192/bin/kilt-app:19:in `load'
    from C:/Ruby192/bin/kilt-app:19:in `<main>'
```

I tried updating the RestClient with 'gem update' but it still doesn't work.  Is there a problem with the way I'm trying to update?

**Comment by dcrec1** [comment]
I thinks its a problem with the ruby-snarl gem. I didn't make the Windows port, so I'll ask the person what version of ruby-snarl where he using, can be a conflict with older/newer versions.

**Comment by ashokraju** [comment]
Hmm I see.  Cool, thanks for the response.  Let me know if you've found a solution.

Appreciate the help!

**Comment by schaable** [comment]
Someone has found a fix for this issue?
