### ISSUE TITLE
Error installing Kilt

### ISSUE THREAD

**Issue by joshbuhler** [dcrec1/kilt#6]
After running the gem install command, I'm getting the following: HTTP Response 302 fetching http://gems.rubyforge.org/yaml

Any suggestions?

**Comment by dcrec1** [comment]
Hi, no it's ok for me. Are you still having this problem? Could be a temporally server instability.

**Comment by joshbuhler** [comment]
Got it installed. Looks like the problem was that I had an old version of gems installed. I updated to 1.8.7, and was able to install just fine.
